spring:
  application:
    name: search_engine_mcp
  ai:
    mcp:
      server:
        name: mcp-search-gateway
        version: 1.0.0
        annotation-scanner:
          enabled: false
search:
  tools:
    - name: call_google
      description: Search using Google
      method: GET
      url: https://www.google.com/search?q={search_query}

    - name: call_yahoo
      description: Search using Yahoo
      method: GET
      url: https://search.yahoo.com/search?p={search_query}



